# -*- coding: utf-8 -*-
"""Arabic_Inquiries_BERT_v2_5CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WeX1zZvxishGTjeDzzmyg4XCbwJNJ1o9

# =========================================================
# 📦 INSTALL DEPENDENCIES
# =========================================================
"""

# 1. إزالة النسخ القديمة تماماً لتجنب أي تضارب
!pip uninstall -y torch torchvision torchaudio

# 2. تثبيت نسخة PyTorch 2.6 المستقرة والآمنة والمتوافقة مع كولاب (CUDA 12.1)
!pip install torch>=2.6.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

# 3. تحديث مكتبات Hugging Face لتتوافق مع التحديث الأمني الجديد
!pip install --upgrade transformers datasets scikit-learn huggingface_hub -q

"""# =========================================================
# 🔐 HUGGING FACE NOTEBOOK LOGIN
# =========================================================
"""

# استيراد أداة تسجيل الدخول التفاعلي لربط النوت بوك بحسابك على Hugging Face بأمان
from huggingface_hub import notebook_login
notebook_login()#تواصل مع صاحب الكود للحصول عليه

"""# =========================================================
# 📚 IMPORT LIBRARIES
# =========================================================
"""

import os
import json
import zipfile
import random
from datetime import datetime
from collections import Counter

import numpy as np
import pandas as pd
import torch
import seaborn as sns
import matplotlib.pyplot as plt

# مكتبات تقسيم البيانات وحساب مقاييس الأداء من Scikit-Learn
from sklearn.model_selection import StratifiedKFold, StratifiedShuffleSplit
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix

# مكتبات Hugging Face لإدارة البيانات وتدريب النماذج الذكية
from datasets import load_dataset, Dataset, ClassLabel
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding,
    EarlyStoppingCallback
)

"""# =========================================================
#🎯 SEED
# =========================================================
"""

# 🎯 دالة تثبيت الـ Seed وتفعيل الحتمية الصارمة على مستوى البيئة لمنع التغيير عند إعادة التشغيل وحل خطأ CuBLAS
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # إعداد مساحة العملـ
    os.environ['CUBLAS_WORKSPACE_CONFIG'] = ':4096:8'
    os.environ['PYTHONHASHSEED'] = str(seed)



# استدعاء أولي لتثبيت البيئة منذ البداية
set_seed(42)

"""# =========================================================
# ⚙️ GPU CHECK
# =========================================================
"""

# التحقق من توفر الـ GPU لضمان تسريع عملية تدريب النموذج
print("CUDA available:", torch.cuda.is_available())

# تحديد الجهاز المستخدم (إن وجد GPU يتم اعتماده، وإلا يتم العودة للـ CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

"""# =========================================================
# 📊 LOAD DATASET
# =========================================================
"""

# 1. تحميل مجموعة بيانات استفسارات الطلاب من الـ Hub
dataset = load_dataset("daliaalkelani/University_Student_Inquiries_Dataset_new3")

# 2. استخراج قائمة بأسماء الكلاسات (الفئات) الفريدة وترتيبها أبجدياً
GLOBAL_LABELS_LIST = sorted(list(set(dataset["train"]["label"])))

# 3. إنشاء قواميس للتحويل الديناميكي بين النص والرقم (ضروري للنموذج)
label2id = {l: i for i, l in enumerate(GLOBAL_LABELS_LIST)}
id2label = {i: l for l, i in label2id.items()}

# 4. تحويل عمود الـ label في البيانات إلى نوع ClassLabel ليتعرف عليه الـ Trainer تلقائياً
dataset["train"] = dataset["train"].cast_column(
    "label",
    ClassLabel(names=GLOBAL_LABELS_LIST)
)

# 5. تحويل النصوص والليبلز إلى مصفوفات NumPy لتسهيل عملية التقسيم اللاحقة
texts = np.array(dataset["train"]["text"])
labels_arr = np.array(dataset["train"]["label"])

print("✔ Labels جاهزة وثابتة")
print("عدد الكلاسات الفعلي داخل الداتا:", len(GLOBAL_LABELS_LIST))

"""# =========================================================
# 🔁 STRATIFIED 5-FOLD SPLIT
# =========================================================
"""

# إعداد بروتوكول التقسيم الطبقي الخماسي الموحد لكل النماذج لضمان المقارنة العادلة
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
folds = []

for train_idx, test_idx in skf.split(texts, labels_arr):
    sub_texts = texts[train_idx]
    sub_labels = labels_arr[train_idx]
    sss = StratifiedShuffleSplit(n_splits=1, test_size=0.1, random_state=42)
    for sub_train_idx, val_idx in sss.split(sub_texts, sub_labels):
        folds.append({
            "train": Dataset.from_dict({"text": sub_texts[sub_train_idx], "label": sub_labels[sub_train_idx]}),
            "val": Dataset.from_dict({"text": sub_texts[val_idx], "label": sub_labels[val_idx]}),
            "test": Dataset.from_dict({"text": texts[test_idx], "label": labels_arr[test_idx]})
        })

# مخزن البيانات الرئيسي لتجميع مخرجات كل نموذج بشكل مستقل
ALL_RESULTS_STORE = {}
print(f"✔ تم إنشاء وتثبيت {len(folds)} فولدات بنجاح.")

"""# =========================================================
#DATA OVERVIEW
# =========================================================

"""

print("==========================================================================================")
print(" فحص التوزيع الطبقي التفصيلي (Stratification Check) لجميع الأقسام في الـ 5 Folds")
print("==========================================================================================\n")

# 1. حساب التوزيع في الداتا الأصلية كاملة كمرجع (Reference)
full_labels = [id2label[lbl] for lbl in dataset["train"]["label"]]
df_full = pd.DataFrame({"Label": full_labels})
full_counts = df_full["Label"].value_counts()
full_pct = df_full["Label"].value_counts(normalize=True) * 100

print(" [توزيع البيانات الأصلية كاملة قبل التقسيم]:")
for k in full_counts.index:
    print(f"   🔹 {k}: {full_counts[k]} جملة ({full_pct[k]:.2f}%)")
print("-" * 60)

# 2. المرور على كل فولد وعرض نسب الأقسام الثلاثة (Train, Val, Test)
for i, fold in enumerate(folds):
    print(f"\n{'#'*30} 📂 FOLD {i+1} {'#'*30}")

    # بناء جدول يحتوي على الإحصائيات الفردية للأقسام
    stats_dict = {}

    for name in ["train", "val", "test"]:
        fold_labels = [id2label[lbl] for lbl in fold[name]["label"]]
        df_sub = pd.DataFrame({"Label": fold_labels})

        counts = df_sub["Label"].value_counts()
        pct = df_sub["Label"].value_counts(normalize=True) * 100

        # دمج العدد والنسبة المئوية في نص واحد منسق
        stats_dict[name.upper()] = {
            k: f"{counts[k]} جملة ({pct[k]:.1f}%)" for k in counts.index
        }

    # تحويل الإحصائيات إلى DataFrame لعرضها كجدول أنيق
    df_fold_strat = pd.DataFrame(stats_dict)
    display(df_fold_strat)

    print(f"📍 إجمالي الحجم في فولد {i+1} -> Train: {len(fold['train'])} | Val: {len(fold['val'])} | Test: {len(fold['test'])}")
    print("=" * 75)

"""# =========================================================
# 🤖 MODELS CONFIGURATION
# =========================================================
"""

MODEL_CONFIGS = {
    "AraBERTv2": "aubmindlab/bert-base-arabertv02",
    "MARBERTv2": "UBC-NLP/MARBERTv2",
    "ARBERTv2": "UBC-NLP/ARBERTv2"
}

"""# =========================================================
# 📊 METRICS
# =========================================================
"""

def compute_metrics(pred):
    logits = pred.predictions
    y_true = pred.label_ids
    y_pred = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "precision_macro": precision_score(y_true, y_pred, average="macro", zero_division=0),
        "recall_macro": recall_score(y_true, y_pred, average="macro", zero_division=0),
        "f1_macro": f1_score(y_true, y_pred, average="macro", zero_division=0),
    }
print("✔ تم بناء إعدادات المقارنة القياسية.")

"""# =========================================================
# AraBERTv2
# =========================================================

"""

model_key = "AraBERTv2"
model_path = MODEL_CONFIGS[model_key]
print(f"🎬 انطلاق تدريب النموذج: {model_key}\n" + "="*50)

tokenizer = AutoTokenizer.from_pretrained(model_path)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def preprocess_1(batch):
    tokenized = tokenizer(batch["text"], padding=True, truncation=True, max_length=128)
    tokenized["labels"] = batch["label"]
    return tokenized

fold_accs, fold_f1s, fold_precs, fold_recs, best_epochs = [], [], [], [], []
all_preds, all_labels = [], []

for i, fold in enumerate(folds):
    print(f"🚀 {model_key} - الـ Fold الحالي: {i+1}/5 جاري التدريب الآن...")
    set_seed(42)

    train_data = fold["train"].map(preprocess_1, batched=True, load_from_cache_file=False)
    val_data   = fold["val"].map(preprocess_1, batched=True, load_from_cache_file=False)
    test_data  = fold["test"].map(preprocess_1, batched=True, load_from_cache_file=False)

    model = AutoModelForSequenceClassification.from_pretrained(
        model_path, num_labels=len(GLOBAL_LABELS_LIST), id2label=id2label, label2id=label2id
    ).to(device)

    args = TrainingArguments(
        output_dir=f"./{model_key}_f{i+1}", eval_strategy="epoch", save_strategy="epoch",
        logging_strategy="epoch", logging_steps=1,
        learning_rate=2e-5, per_device_train_batch_size=16, per_device_eval_batch_size=16,
        num_train_epochs=10, weight_decay=0.01, fp16=True, load_best_model_at_end=True,
        metric_for_best_model="eval_loss", greater_is_better=False, seed=42, data_seed=42,
    )

    trainer = Trainer(
        model=model, args=args, train_dataset=train_data, eval_dataset=val_data,
        compute_metrics=compute_metrics, data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]  # 🛠️ تم تصحيح الكلمة هنا
    )
    trainer.train()

    # حساب الأيبوك الأفضل للفولد الحالي
    actual_stopped_epoch = int(np.ceil(trainer.state.epoch))
    best_ckpt = trainer.state.best_model_checkpoint
    if best_ckpt:
        b_epoch = round((int(best_ckpt.split("-")[-1]) / trainer.state.global_step) * trainer.state.epoch)
    else:
        b_epoch = actual_stopped_epoch
    b_epoch = max(1, min(b_epoch, actual_stopped_epoch))
    best_epochs.append(b_epoch)

    # التنبؤ وجمع المقاييس وحفظها في الـ RAM
    preds = trainer.predict(test_data)
    y_pred = np.argmax(preds.predictions, axis=1)

    fold_accs.append(accuracy_score(preds.label_ids, y_pred))
    fold_f1s.append(f1_score(preds.label_ids, y_pred, average="macro"))
    fold_precs.append(precision_score(preds.label_ids, y_pred, average="macro", zero_division=0))
    fold_recs.append(recall_score(preds.label_ids, y_pred, average="macro", zero_division=0))
    all_preds.extend(y_pred)
    all_labels.extend(preds.label_ids)

    # 🧹 مكنسة تفريغ الديسك التلقائي بعد حفظ البيانات بالـ RAM
    !rm -rf {args.output_dir}
    print(f"🗑️ تنظيف تلقائي ناجح ومسح مجلد: {args.output_dir}")

    torch.cuda.empty_cache()

# حساب الأيبوك الشاملة الأكثر تكراراً والمتوسطات النهائية
global_best_epoch = Counter(best_epochs).most_common(1)[0][0]

ALL_RESULTS_STORE[model_key] = {
    "acc": np.mean(fold_accs), "f1": np.mean(fold_f1s), "prec": np.mean(fold_precs), "rec": np.mean(fold_recs),
    "epoch_mode": global_best_epoch, "preds": all_preds, "labels": all_labels, "fold_accs": fold_accs, "fold_f1s": fold_f1s
}

print("\n" + "="*50)
print(f"📊 [الملخص النهائي الشامل للنموذج: {model_key}]")
print(f"⭐ أفضل إيبوك نهائية معتمدة (Global Best Epoch): {global_best_epoch}")
print(f"🎯 متوسط الـ Accuracy النهائي : {np.mean(fold_accs):.4f}")
print(f"📈 متوسط الـ F1-Score النهائي  : {np.mean(fold_f1s):.4f}")
print(f"🔍 متوسط الـ Precision النهائي : {np.mean(fold_precs):.4f}")
print(f"🔄 متوسط الـ Recall النهائي    : {np.mean(fold_recs):.4f}")
print("="*50 + "\n✔ تم الحفظ والانتهاء بنجاح!")

"""# =========================================================
# ARBERTv2
# =========================================================

"""

model_key = "ARBERTv2"
model_path = MODEL_CONFIGS[model_key]
print(f"🎬 انطلاق تدريب النموذج: {model_key}\n" + "="*50)

tokenizer = AutoTokenizer.from_pretrained(model_path)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

def preprocess_2(batch):
    tokenized = tokenizer(batch["text"], padding=True, truncation=True, max_length=128)
    tokenized["labels"] = batch["label"]
    return tokenized

fold_accs, fold_f1s, fold_precs, fold_recs, best_epochs = [], [], [], [], []
all_preds, all_labels = [], []

for i, fold in enumerate(folds):
    print(f"🚀 {model_key} - الـ Fold الحالي: {i+1}/5 جاري التدريب الآن...")
    set_seed(42)

    train_data = fold["train"].map(preprocess_2, batched=True, load_from_cache_file=False)
    val_data   = fold["val"].map(preprocess_2, batched=True, load_from_cache_file=False)
    test_data  = fold["test"].map(preprocess_2, batched=True, load_from_cache_file=False)

    model = AutoModelForSequenceClassification.from_pretrained(
        model_path, num_labels=len(GLOBAL_LABELS_LIST), id2label=id2label, label2id=label2id
    ).to(device)

    args = TrainingArguments(
        output_dir=f"./{model_key}_f{i+1}", eval_strategy="epoch", save_strategy="epoch",
        logging_strategy="epoch", logging_steps=1,
        learning_rate=2e-5, per_device_train_batch_size=16, per_device_eval_batch_size=16,
        num_train_epochs=10, weight_decay=0.01, fp16=True, load_best_model_at_end=True,
        metric_for_best_model="eval_loss", greater_is_better=False, seed=42, data_seed=42,
    )

    trainer = Trainer(
        model=model, args=args, train_dataset=train_data, eval_dataset=val_data,
        compute_metrics=compute_metrics, data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
    )
    trainer.train()

    # حساب الأيبوك الأفضل للفولد الحالي
    actual_stopped_epoch = int(np.ceil(trainer.state.epoch))
    best_ckpt = trainer.state.best_model_checkpoint
    if best_ckpt:
        b_epoch = round((int(best_ckpt.split("-")[-1]) / trainer.state.global_step) * trainer.state.epoch)
    else:
        b_epoch = actual_stopped_epoch
    b_epoch = max(1, min(b_epoch, actual_stopped_epoch))
    best_epochs.append(b_epoch)

    # التنبؤ وجمع المقاييس وحفظها في الـ RAM
    preds = trainer.predict(test_data)
    y_pred = np.argmax(preds.predictions, axis=1)

    fold_accs.append(accuracy_score(preds.label_ids, y_pred))
    fold_f1s.append(f1_score(preds.label_ids, y_pred, average="macro"))
    fold_precs.append(precision_score(preds.label_ids, y_pred, average="macro", zero_division=0))
    fold_recs.append(recall_score(preds.label_ids, y_pred, average="macro", zero_division=0))
    all_preds.extend(y_pred)
    all_labels.extend(preds.label_ids)

    # 🧹 مكنسة تفريغ الديسك التلقائي بعد حفظ البيانات بالـ RAM
    !rm -rf {args.output_dir}
    print(f"🗑️ تنظيف تلقائي ناجح ومسح مجلد: {args.output_dir}")

    torch.cuda.empty_cache()

# حساب الأيبوك الشاملة الأكثر تكراراً والمتوسطات النهائية
global_best_epoch = Counter(best_epochs).most_common(1)[0][0]

ALL_RESULTS_STORE[model_key] = {
    "acc": np.mean(fold_accs), "f1": np.mean(fold_f1s), "prec": np.mean(fold_precs), "rec": np.mean(fold_recs),
    "epoch_mode": global_best_epoch, "preds": all_preds, "labels": all_labels, "fold_accs": fold_accs, "fold_f1s": fold_f1s
}

print("\n" + "="*50)
print(f"📊 [الملخص النهائي الشامل للنموذج: {model_key}]")
print(f"⭐ أفضل إيبوك نهائية معتمدة (Global Best Epoch): {global_best_epoch}")
print(f"🎯 متوسط الـ Accuracy النهائي : {np.mean(fold_accs):.4f}")
print(f"📈 متوسط الـ F1-Score النهائي  : {np.mean(fold_f1s):.4f}")
print(f"🔍 متوسط الـ Precision النهائي : {np.mean(fold_precs):.4f}")
print(f"🔄 متوسط الـ Recall النهائي    : {np.mean(fold_recs):.4f}")
print("="*50 + "\n✔ تم الحفظ والانتهاء بنجاح!")

"""# =========================================================
# MARBERTv2
# =========================================================

"""

model_key = "MARBERTv2"
model_path = MODEL_CONFIGS[model_key]
print(f"🎬 انطلاق تدريب النموذج: {model_key}\n" + "="*50)

tokenizer = AutoTokenizer.from_pretrained(model_path)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# تم تغيير اسم الدالة ديناميكياً لتتوافق مع استدعاء ماربيرت المستقل
def preprocess_marbert(batch):
    tokenized = tokenizer(batch["text"], padding=True, truncation=True, max_length=128)
    tokenized["labels"] = batch["label"]
    return tokenized

fold_accs, fold_f1s, fold_precs, fold_recs, best_epochs = [], [], [], [], []
all_preds, all_labels = [], []

for i, fold in enumerate(folds):
    print(f"🚀 {model_key} - الـ Fold الحالي: {i+1}/5 جاري التدريب الآن...")
    set_seed(42)

    train_data = fold["train"].map(preprocess_marbert, batched=True, load_from_cache_file=False)
    val_data   = fold["val"].map(preprocess_marbert, batched=True, load_from_cache_file=False)
    test_data  = fold["test"].map(preprocess_marbert, batched=True, load_from_cache_file=False)

    # 👑 تم تثبيت الحل السحري الخاص بكِ لكسر قيود الحماية بأمان
    model = AutoModelForSequenceClassification.from_pretrained(
        model_path,
        num_labels=len(GLOBAL_LABELS_LIST),
        id2label=id2label,
        label2id=label2id,
        use_safetensors=True
    ).to(device)

    args = TrainingArguments(
        output_dir=f"./{model_key}_f{i+1}", eval_strategy="epoch", save_strategy="epoch",
        logging_strategy="epoch", logging_steps=1,
        learning_rate=2e-5, per_device_train_batch_size=16, per_device_eval_batch_size=16,
        num_train_epochs=10, weight_decay=0.01, fp16=True, load_best_model_at_end=True,
        metric_for_best_model="eval_loss", greater_is_better=False, seed=42, data_seed=42
    )

    trainer = Trainer(
        model=model, args=args, train_dataset=train_data, eval_dataset=val_data,
        compute_metrics=compute_metrics, data_collator=data_collator,
        callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
    )
    trainer.train()

    actual_stopped_epoch = int(np.ceil(trainer.state.epoch))
    best_ckpt = trainer.state.best_model_checkpoint
    if best_ckpt:
        b_epoch = round((int(best_ckpt.split("-")[-1]) / trainer.state.global_step) * trainer.state.epoch)
    else:
        b_epoch = actual_stopped_epoch
    b_epoch = max(1, min(b_epoch, actual_stopped_epoch))
    best_epochs.append(b_epoch)

    preds = trainer.predict(test_data)
    y_pred = np.argmax(preds.predictions, axis=1)

    fold_accs.append(accuracy_score(preds.label_ids, y_pred))
    fold_f1s.append(f1_score(preds.label_ids, y_pred, average="macro"))
    fold_precs.append(precision_score(preds.label_ids, y_pred, average="macro", zero_division=0))
    fold_recs.append(recall_score(preds.label_ids, y_pred, average="macro", zero_division=0))
    all_preds.extend(y_pred)
    all_labels.extend(preds.label_ids)

    # 🧹 مكنسة الديسك الذكية والأوتوماتيكية: تنظف المجلد الضخم فوراً بعد تجميع البيانات في الـ RAM
    !rm -rf {args.output_dir}
    print(f"🗑️ تنظيف تلقائي ناجح: تم تفريغ المساحة ومسح مجلد الفولد المنتهي: {args.output_dir}")

    torch.cuda.empty_cache()

global_best_epoch = Counter(best_epochs).most_common(1)[0][0]

ALL_RESULTS_STORE[model_key] = {
    "acc": np.mean(fold_accs), "f1": np.mean(fold_f1s), "prec": np.mean(fold_precs), "rec": np.mean(fold_recs),
    "epoch_mode": global_best_epoch, "preds": all_preds, "labels": all_labels, "fold_accs": fold_accs, "fold_f1s": fold_f1s
}

# 📊 طباعة الملخص النهائي الكلي للنموذج الثالث
print("\n" + "="*50)
print(f"📊 [الملخص النهائي الشامل للنموذج: {model_key}]")
print(f"⭐ أفضل إيبوك نهائية معتمدة (Global Best Epoch): {global_best_epoch}")
print(f"🎯 متوسط الـ Accuracy النهائي : {np.mean(fold_accs):.4f}")
print(f"📈 متوسط الـ F1-Score النهائي  : {np.mean(fold_f1s):.4f}")
print(f"🔍 متوسط الـ Precision النهائي : {np.mean(fold_precs):.4f}")
print(f"🔄 متوسط الـ Recall النهائي    : {np.mean(fold_recs):.4f}")
print("="*50 + "\n✔ تم الحفظ والانتهاء بنجاح والمساحة خضراء!")

"""# =========================================================
# 📉 CONFUSION MATRIX
# =========================================================
"""

# 📉 رسم مصفوفة الارتباك الثلاثية المقارنة بشكل موحد
correct_class_names = [id2label[k] for k in sorted(id2label.keys())]
fig, axes = plt.subplots(1, 3, figsize=(22, 6))

# سحب النماذج المتوفرة في المخزن تلقائياً لمنع أي كراش
available_models = list(ALL_RESULTS_STORE.keys())

for idx, model_key in enumerate(available_models):
    summary = ALL_RESULTS_STORE[model_key]
    cm = confusion_matrix(summary["labels"], summary["preds"])

    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=correct_class_names, yticklabels=correct_class_names,
                ax=axes[idx], cbar=False)

    axes[idx].set_title(f"Confusion Matrix: {model_key}", fontsize=12, fontweight='bold')
    axes[idx].set_xlabel("Predicted")
    axes[idx].set_ylabel("True")

# إخفاء المحاور الزائدة إذا كان عدد النماذج الجاهزة أقل من 3
for j in range(len(available_models), 3):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""# =========================================================
# ❌ ERROR ANALYSIS
# =========================================================
"""

# Loop through all models stored in RAM
for model_key, summary in ALL_RESULTS_STORE.items():
    total_samples = len(summary["labels"])
    wrong_count = sum(np.array(summary["labels"]) != np.array(summary["preds"]))
    error_rate = (wrong_count / total_samples) * 100
    f1_stdev = np.std(summary['fold_f1s'])

    # Format the header section for each model
    print("\n" + "="*75)
    print(f"📊 PERFORMANCE EVALUATION REPORT: {model_key.upper()}")
    print("="*75)
    print(f" 🔹 Total Test Samples      : {total_samples}")
    print(f" 🔹 Total Classification Errs: {wrong_count}")
    print(f" 🔹 Overall Error Rate      : {error_rate:.2f}%")
    print(f" 🔹 Cross-Fold Stability    : {f1_stdev:.4f} (F1 StdDev)")
    print("\n 🔍 [Detailed Confusion & Misclassification Analysis]:")
    print(" -------------------------------------------------------------------------")

    # Compute the full confusion matrix for the current model
    cm_model = confusion_matrix(summary["labels"], summary["preds"])

    pairs = []
    for i in range(cm_model.shape[0]):
        for j in range(cm_model.shape[0]):
            # i is the Ground Truth, j is the Incorrectly Predicted class
            if i != j and cm_model[i][j] > 0:
                pairs.append((correct_class_names[i], correct_class_names[j], cm_model[i][j]))

    # Sort the misclassifications descendingly by their frequency
    pairs = sorted(pairs, key=lambda x: x[2], reverse=True)

    if pairs:
        # Print all errors formatted cleanly
        print(f"    {'No.':<4} | {'Ground Truth Class':<25} ➔ {'Misclassified As':<25} | {'Count':<5}")
        print("    " + "-"*69)
        for idx, (true_cls, pred_cls, count) in enumerate(pairs, 1):
            print(f"    {idx:<4} | {true_cls:<25} ➔ {pred_cls:<25} | {count:<5} times")
    else:
        print("    🎉 Exceptional Performance! No misclassifications recorded for this model.")

    print("="*75 + "\n")

# 1. تجميع البيانات مباشرة من مخزن النتائج الإجمالي
error_chart_data = []

for model_key, summary in ALL_RESULTS_STORE.items():
    all_labels = summary["labels"]
    all_preds = summary["preds"]

    # حساب عدد الأخطاء الصافي
    num_errors = sum(1 for idx in range(len(all_labels)) if all_labels[idx] != all_preds[idx])

    error_chart_data.append({
        "Model": model_key,
        "Total Errors": num_errors
    })

# 2. تحويل البيانات وتجهيز الرسم
df_errors_only = pd.DataFrame(error_chart_data)
sns.set_theme(style="whitegrid")
plt.figure(figsize=(9, 5.5))

# 3. بناء المخطط البياني بتدرج الألوان الحمراء الأكاديمية
ax_err = sns.barplot(
    x="Model",
    y="Total Errors",
    data=df_errors_only,
    palette="Reds_r",
    edgecolor="black",
    linewidth=1.2
)

# 4. العناوين والمسميات التوضيحية للمحاور
plt.title("Total Classification Errors Across Tested Models\n(Lower is Better)", fontsize=13, fontweight='bold', pad=15)
plt.ylabel("Number of Misclassified Samples", fontsize=11, fontweight='bold')
plt.xlabel("Evaluated Models", fontsize=11, fontweight='bold')

# 5. طباعة الرقم الفعلي للأخطاء فوق كل عمود بياني بشكل مرتب
for p in ax_err.patches:
    height = p.get_height()
    ax_err.annotate(
        f'{int(height)} Errors',
        (p.get_x() + p.get_width() / 2., height),
        ha='center',
        va='center',
        xytext=(0, 8),
        textcoords='offset points',
        fontsize=10,
        fontweight='bold',
        color='black'
    )

plt.tight_layout()

# 6. 🔥 عرض المخطط مباشرة على الشاشة تحت الخلية
plt.show()

import os
from IPython.display import display, HTML

# 1. استخراج المقارنات والإحصائيات ديناميكياً وبشكل صحيح من مخزن النتائج ALL_RESULTS_STORE
extracted_metrics = []

for model_key, summary in ALL_RESULTS_STORE.items():
    all_labels = summary["labels"]
    all_preds = summary["preds"]
    total_samples = len(all_labels)

    # حساب عدد الأخطاء والإصابات الصحيحة من البيانات الفعلية
    num_errors = sum(1 for idx in range(total_samples) if all_labels[idx] != all_preds[idx])
    correct_preds = total_samples - num_errors

    # استرجاع مقاييس الأداء الحقيقية بدقة من مفاتيحها الصحيحة الصغرى
    f1_score = float(summary.get("f1", 0.0))
    precision = float(summary.get("prec", 0.0))
    recall = float(summary.get("rec", 0.0))
    raw_accuracy = float(summary.get("acc", 0.0))

    # التحقق مما إذا كانت الـ Accuracy مخزنة كنسبة مئوية أو ككسر عشري لتصحيح العرض
    if raw_accuracy <= 1.0:
        accuracy_percentage = raw_accuracy * 100
    else:
        accuracy_percentage = raw_accuracy

    extracted_metrics.append({
        "model": model_key,
        "total_samples": total_samples,
        "correct": correct_preds,
        "errors": num_errors,
        "accuracy": round(accuracy_percentage, 2),
        "f1": round(f1_score, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4)
    })

# 2. بناء هيكل الـ HTML المخصص لعرض الجدول الأكاديمي الصافي فقط
html_table_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Academic Evaluation Matrix</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono&display=swap" rel="stylesheet">
    <style>
        :root {{
            --primary-color: #0f172a;
            --text-color: #334155;
            --border-color: #e2e8f0;
            --accent-red: #991b1b;
            --accent-green: #166534;
            --bg-light: #f8fafc;
        }}

        body {{
            font-family: 'Inter', sans-serif;
            color: var(--text-color);
            line-height: 1.6;
            background-color: #ffffff;
            margin: 0;
            padding: 20px;
        }}

        .container {{
            max-width: 1100px;
            margin: 0 auto;
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
            font-size: 13.5px;
        }}

        th {{
            border-top: 1.5px solid var(--primary-color);
            border-bottom: 1.5px solid var(--primary-color);
            color: var(--primary-color);
            font-weight: 600;
            padding: 12px 14px;
            text-align: left;
            background-color: var(--bg-light);
        }}

        td {{
            border-bottom: 1px solid var(--border-color);
            padding: 12px 14px;
        }}

        tr:last-child td {{
            border-bottom: 1.5px solid var(--primary-color);
        }}

        .mono {{
            font-family: 'JetBrains Mono', monospace;
            font-size: 12.5px;
            font-weight: 500;
        }}

        .bold {{ font-weight: 600; }}
        .error-text {{ color: var(--accent-red); font-weight: 600; }}
        .success-text {{ color: var(--accent-green); font-weight: 600; }}
    </style>
</head>
<body>

<div class="container">

    <table>
        <thead>
            <tr>
                <th>Model Identifier</th>
                <th>Total Deployed</th>
                <th>Correct Cls</th>
                <th>Total Errors</th>
                <th>Accuracy (%)</th>
                <th>Precision</th>
                <th>Recall</th>
                <th>Macro F1-Score</th>
            </tr>
        </thead>
        <tbody>
        """

# إدراج صفوف النتائج الفعلية ديناميكياً
for row in extracted_metrics:
    is_top = "bold" if row["f1"] >= 0.92 else ""
    html_table_content += f"""
            <tr class="{is_top}">
                <td class="mono">{row["model"]}</td>
                <td>{row["total_samples"]}</td>
                <td class="success-text">{row["correct"]}</td>
                <td class="error-text">{row["errors"]}</td>
                <td>{row["accuracy"]}%</td>
                <td>{row["precision"]:.4f}</td>
                <td>{row["recall"]:.4f}</td>
                <td style="background-color: rgba(30,58,138,0.04); font-weight:700;">{row["f1"]:.4f}</td>
            </tr>
    """

html_table_content += f"""
        </tbody>
    </table>

</div>

</body>
</html>
"""

# 3. حفظ الجدول الصافي كملف مستقل لتوثيق المشروع
output_filename = "model_comparison_table.html"
with open(output_filename, "w", encoding="utf-8") as f:
    f.write(html_table_content)

# 4. عرض الجدول النقي تفاعلياً ومباشرة داخل الخلية
print("🎯 Academic Evaluation Table generated successfully (Pure Layout)!")
print("-" * 80)

display(HTML(html_table_content))

# 1. إعادة ترتيب البيانات في جدول (DataFrame) مريح ومنظم
data = {
    'Fold': ['Fold 1', 'Fold 2', 'Fold 3', 'Fold 4', 'Fold 5'] * 3,
    'Model': ['MARBERTv2']*5 + ['ARBERTv2']*5 + ['AraBERTv2']*5,
    'Optimal Epoch': [3, 2, 2, 2, 3] + [3, 1, 1, 1, 2] + [5, 2, 2, 4, 2]
}
df = pd.DataFrame(data)

# 2. إعداد مظهر أكاديمي بسيط ومريح للعين
sns.set_theme(style="whitegrid")
plt.figure(figsize=(11, 6)) # تم تكبير العرض قليلاً ليعطي مساحة مريحة للصندوق الجانبي

# اختيار لوحة ألوان هادئة ومتناسقة وغير فاقعة
colors = ['#b91c1c', '#1d4ed8', '#0f766e'] # أحمر رصين، أزرق رصين، تيل داكن

# رسم الأعمدة المجمعة بنقاء عالي
ax = sns.barplot(
    x='Fold',
    y='Optimal Epoch',
    hue='Model',
    data=df,
    palette=colors,
    edgecolor='black',
    linewidth=0.8,
    alpha=0.9
)

# 3. إضافة الأرقام فوق الأعمدة بشكل شفاف ونظيف بدون تداخل
for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{int(height)}',
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center',
                    xytext=(0, 6),
                    textcoords='offset points',
                    fontsize=9.5,
                    fontweight='bold',
                    color='#334155')

# 4. إضافة صندوق الـ Global Best Epoch على طرف الرسمة بشكل أنيق
# النص المراد عرضه بالصندوق بناءً على حساب الـ Mode (الأكثر تكراراً)
best_epochs_text = (
    "Global Best Epochs:\n"
    "▪ MARBERTv2 : Epoch 2\n"
    "▪ ARBERTv2    : Epoch 1\n"
    "▪ AraBERTv2  : Epoch 2"
)

# وضع الصندوق في مكان استراتيجي (بين الفولد الثالث والرابع علوياً لتجنب تداخل الـ Legend)
plt.text(2.1, 4.6, best_epochs_text, fontsize=10, fontweight='bold',
         bbox=dict(facecolor='#f8fafc', alpha=0.95, boxstyle='round,pad=0.6', edgecolor='#cbd5e1', linewidth=1),
         color='#1e293b', linespacing=1.5)

# 5. تنسيق المحاور والعناوين لتقليل العجقة البصرية
plt.title("Model Convergence Across 5-Fold Validation (Optimal Epochs)", fontsize=13, fontweight='bold', pad=15)
plt.xlabel("Validation Folds", fontsize=11, fontweight='bold', labelpad=10)
plt.ylabel("Epochs to Converge", fontsize=11, fontweight='bold', labelpad=10)

# ضبط المدى لتوفير مساحة علوية مريحة للأرقام والصندوق
plt.ylim(0, 6)
plt.yticks(range(1, 7))

# تحسين مظهر صندوق التوضيح (Legend)
plt.legend(title="Architectures", loc='upper right', frameon=True, facecolor='#ffffff', edgecolor='#e2e8f0')

# تنظيف الإطار العام
sns.despine(left=True, bottom=True)
plt.tight_layout()

# 6. حفظ الرسمة النظيفة في المجلد المخصص للفريق
report_dir = "academic_models_evaluation_report/1_Global_Analysis"
os.makedirs(report_dir, exist_ok=True)
plt.savefig(os.path.join(report_dir, "cross_fold_epochs_clean.png"), dpi=300)
plt.show()

print("✔ تم تعديل الرسمة وإضافة ملخص الـ Best Epochs الجانبي وحفظها بنجاح!")

import pandas as pd
import numpy as np
from IPython.display import display
import ipywidgets as widgets

def build_error_table(model_key, summary):
    y_true = np.array(summary["labels"])
    y_pred = np.array(summary["preds"])

    error_rows = []

    for i in range(len(y_true)):
        if y_true[i] != y_pred[i]:
            error_rows.append({
                "Text": texts[i],
                "True Label": id2label[y_true[i]],
                "Predicted": id2label[y_pred[i]]
            })

    df_errors = pd.DataFrame(error_rows)
    return df_errors


# 🔘 إنشاء أزرار لكل مودل
for model_key, summary in ALL_RESULTS_STORE.items():

    button = widgets.Button(
        description=f"عرض أخطاء {model_key}",
        button_style='danger',
        layout=widgets.Layout(width='250px')
    )

    output = widgets.Output()

    def on_button_click(b, model_key=model_key, summary=summary):
        with output:
            output.clear_output()

            df_errors = build_error_table(model_key, summary)

            print(f"\n🎯 جميع الأخطاء للمودل: {model_key}")
            print(f"🔴 عدد الأخطاء: {len(df_errors)}")
            print("="*80)

            display(df_errors)  # 🔥 الجدول كامل بدون head()

    button.on_click(on_button_click)

    display(button, output)

"""#===============================================================
#📦 Save Results
#================================================================
"""

# 1. إعداد وتصفير المجلد الرئيسي والمجلدات الفرعية الأربعة
base_dir = "academic_models_evaluation_report"
!rm -rf {base_dir} *.zip

dir_global = os.path.join(base_dir, "1_Global_Analysis")
dir_matrices = os.path.join(base_dir, "2_Model_Confusion_Matrices")
dir_errors = os.path.join(base_dir, "3_Model_Misclassifications")
dir_frequencies = os.path.join(base_dir, "4_Detailed_Error_Frequencies")

for folder in [dir_global, dir_matrices, dir_errors, dir_frequencies]:
    os.makedirs(folder, exist_ok=True)

print("🏗️ Building Professional 4-Directory Research Infrastructure for the Team...")
print("-" * 80)

global_summary_metrics = {}
error_summary_records = []
correct_class_names = [id2label[k] for k in sorted(id2label.keys())]

# =========================================================
# 📊 أولاً: بناء وحفظ المخططات العامة المقارنة (المقاييس والإيبوكات)
# =========================================================
# المخطط الأول: مقارنة مقاييس الأداء العامة (Accuracy, F1, etc.)
chart_data = []
metrics_list = ["acc", "f1", "prec", "rec"]
metric_names_mapping = {"acc": "Accuracy", "f1": "F1-Score", "prec": "Precision", "rec": "Recall"}

for model_key, summary in ALL_RESULTS_STORE.items():
    for metric in metrics_list:
        chart_data.append({
            "Model": model_key,
            "Metric": metric_names_mapping[metric],
            "Value": summary[metric]
        })

df_chart = pd.DataFrame(chart_data)
sns.set_theme(style="whitegrid")
plt.figure(figsize=(12, 6))
ax = sns.barplot(x="Metric", y="Value", hue="Model", data=df_chart, palette="muted", edgecolor="black", linewidth=1)
plt.title("Comparative Evaluation Metrics Across Arabic BERT Variants", fontsize=14, fontweight='bold', pad=15)
plt.ylim(0.7, 1.05)

for p in ax.patches:
    height = p.get_height()
    if height > 0:
        ax.annotate(f'{height:.4f}', (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center', xytext=(0, 8), textcoords='offset points', fontsize=9, fontweight='bold')

plt.legend(title="Tested Models", loc='upper right', frameon=True, shadow=True)
plt.tight_layout()

main_chart_path = os.path.join(dir_global, "overall_metrics_comparison.png")
plt.savefig(main_chart_path, dpi=300)
plt.close()
print("✔ Saved: Overall metrics comparison chart -> [1_Global_Analysis/]")

# --- إضافة الرسمة العمودية المنظمة لتحليل استقرار الإيبوكات عبر الفولدات الخمسة دون عجقة بصرية ---
data_epochs = {
    'Fold': ['Fold 1', 'Fold 2', 'Fold 3', 'Fold 4', 'Fold 5'] * 3,
    'Model': ['MARBERTv2']*5 + ['ARBERTv2']*5 + ['AraBERTv2']*5,
    'Optimal Epoch': [3, 2, 2, 2, 3] + [3, 1, 1, 1, 2] + [5, 2, 2, 4, 2]
}
df_epochs = pd.DataFrame(data_epochs)

plt.figure(figsize=(10, 5.5))
colors_epochs = ['#b91c1c', '#1d4ed8', '#0f766e'] # أحمر رصين، أزرق رصين، تيل داكن

ax_epochs = sns.barplot(
    x='Fold',
    y='Optimal Epoch',
    hue='Model',
    data=df_epochs,
    palette=colors_epochs,
    edgecolor='black',
    linewidth=0.8,
    alpha=0.9
)

for p in ax_epochs.patches:
    height = p.get_height()
    if height > 0:
        ax_epochs.annotate(f'{int(height)}',
                    (p.get_x() + p.get_width() / 2., height),
                    ha='center', va='center',
                    xytext=(0, 6),
                    textcoords='offset points',
                    fontsize=9.5,
                    fontweight='bold',
                    color='#334155')

plt.title("Model Convergence Across 5-Fold Validation (Optimal Epochs)", fontsize=13, fontweight='bold', pad=15)
plt.xlabel("Validation Folds", fontsize=11, fontweight='bold', labelpad=10)
plt.ylabel("Epochs to Converge", fontsize=11, fontweight='bold', labelpad=10)
plt.ylim(0, 6)
plt.yticks(range(1, 7))
plt.legend(title="Architectures", loc='upper right', frameon=True, facecolor='#ffffff', edgecolor='#e2e8f0')
sns.despine(left=True, bottom=True)
plt.tight_layout()

epochs_chart_path = os.path.join(dir_global, "cross_fold_epochs_clean.png")
plt.savefig(epochs_chart_path, dpi=300)
plt.close()
print("✔ Saved: Clean cross-fold convergence bar chart -> [1_Global_Analysis/]")


# =========================================================
# 🗂️ ثانياً: فرز البيانات، مصفوفات الارتباك، وجداول التكرار لكل نموذج
# =========================================================
for model_key, summary in ALL_RESULTS_STORE.items():
    print(f"\n🎬 Structuring Assets for Model: {model_key}")

    all_labels = summary["labels"]
    all_preds = summary["preds"]
    total_samples = len(all_labels)

    # تجميع النصوص الأصلية من الفولدات للمطابقة اللغوية
    all_test_texts = []
    for fold in folds:
        all_test_texts.extend([sample["text"] for sample in fold["test"]])

    misclassified_records = []
    for idx in range(total_samples):
        if all_labels[idx] != all_preds[idx]:
            misclassified_records.append({
                "Error_No": len(misclassified_records) + 1,
                "Arabic_Text_Sample": all_test_texts[idx] if idx < len(all_test_texts) else f"Index_{idx}",
                "True_Class": correct_class_names[all_labels[idx]],
                "Predicted_Class": correct_class_names[all_preds[idx]]
            })

    num_errors = len(misclassified_records)
    error_percentage = (num_errors / total_samples) * 100 if total_samples > 0 else 0

    # تجميع سجلات ملخص الأخطاء العام للمجلد الأول
    error_summary_records.append({
        "Model_Name": model_key,
        "Total_Test_Samples": total_samples,
        "Total_Misclassified_Errors": num_errors,
        "Error_Rate_Percentage": round(error_percentage, 2)
    })

    # بناء الجيسون العام للمجلد الأول
    global_summary_metrics[model_key] = {
        "Accuracy": float(summary["acc"]),
        "Precision_Macro": float(summary["prec"]),
        "Recall_Macro": float(summary["rec"]),
        "F1-Score_Macro": float(summary["f1"]),
        "Total_Errors": num_errors,
        "Global_Best_Epoch": int(summary["epoch_mode"]),
        "Cross_Fold_F1_Scores": [float(v) for v in summary["fold_f1s"]],
        "F1_StdDev": float(np.std(summary["fold_f1s"]))
    }

    # 🎨 حفظ مصفوفة الارتباك (المجلد الثاني)
    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=correct_class_names, yticklabels=correct_class_names, cbar=False)
    plt.title(f"Confusion Matrix: {model_key}", fontsize=12, fontweight='bold', pad=10)
    plt.xlabel("Predicted Labels", fontweight='bold')
    plt.ylabel("True Labels", fontweight='bold')
    plt.tight_layout()

    cm_path = os.path.join(dir_matrices, f"{model_key}_confusion_matrix.png")
    plt.savefig(cm_path, dpi=300)
    plt.close()
    print(f"   ✔ Routed: Confusion Matrix image -> [2_Model_Confusion_Matrices/]")

    # 📄 حفظ سجل العينات النصية المخطئة بالكامل (المجلد الثالث)
    if misclassified_records:
        df_errors = pd.DataFrame(misclassified_records)
        errors_csv_path = os.path.join(dir_errors, f"{model_key}_misclassified_examples.csv")
        df_errors.to_csv(errors_csv_path, index=False, encoding="utf-8-sig")
        print(f"   ✔ Routed: Individual errors CSV -> [3_Model_Misclassifications/]")

        # ➔ ➔ ➔ حساب وحفظ تكرارات الأخطاء المحددة (المجلد الرابع المطلوب)
        pairs_counts = {}
        for rec in misclassified_records:
            pair_key = (rec["True_Class"], rec["Predicted_Class"])
            pairs_counts[pair_key] = pairs_counts.get(pair_key, 0) + 1

        sorted_pairs = sorted(pairs_counts.items(), key=lambda x: x[1], reverse=True)

        # 1. حفظها كـ CSV منسق للفريق
        freq_records = []
        for rank, ((true_c, pred_c), count) in enumerate(sorted_pairs, 1):
            freq_records.append({
                "Rank": rank,
                "Ground_Truth_Class": true_c,
                "Misclassified_As": pred_c,
                "Total_Occurrences": count
            })
        df_freq = pd.DataFrame(freq_records)
        freq_csv_path = os.path.join(dir_frequencies, f"{model_key}_error_frequencies.csv")
        df_freq.to_csv(freq_csv_path, index=False, encoding="utf-8-sig")

        # 2. حفظها كتقرير نصي أنيق يشبه طباعة الكود تماماً (.txt) لسهولة القراءة السريعة
        freq_text_path = os.path.join(dir_frequencies, f"{model_key}_error_frequencies_report.txt")
        with open(freq_text_path, "w", encoding="utf-8") as f_txt:
            f_txt.write(f"===========================================================================\n")
            f_txt.write(f"📊 DETAILED MISCLASSIFICATION FREQUENCIES FOR MODEL: {model_key.upper()}\n")
            f_txt.write(f"===========================================================================\n")
            f_txt.write(f"{'No.':<4} | {'Ground Truth Class':<25} ➔ {'Misclassified As':<25} | {'Count':<5}\n")
            f_txt.write("-" * 75 + "\n")
            for rank, ((true_c, pred_c), count) in enumerate(sorted_pairs, 1):
                f_txt.write(f"{rank:<4} | {true_c:<25} ➔ {pred_c:<25} | {count:<5} times\n")
            f_txt.write(f"===========================================================================\n")
        print(f"   ✔ Routed: Detailed transition frequencies (CSV & TXT) -> [4_Detailed_Error_Frequencies/]")
    else:
        print("   🎉 Exceptional performance! No errors found to process for this model.")

print("-" * 80)

# =========================================================
# 📄 Location 3: إخراج تقارير المجلد الأول النهائية
# =========================================================
json_path = os.path.join(dir_global, "global_evaluation_summary.json")
with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(global_summary_metrics, f, ensure_ascii=False, indent=4)

df_err_summary = pd.DataFrame(error_summary_records)
err_summary_path = os.path.join(dir_global, "error_distribution_summary.csv")
df_err_summary.to_csv(err_summary_path, index=False, encoding="utf-8-sig")

print("✔ Generated master files inside [1_Global_Analysis/]")

# =========================================================
# 🗜️ رابعاً: الأرشفة والضغط للتحميل التلقائي للمتصفح
# =========================================================
zip_filename = "academic_models_evaluation_report.zip"
print("-" * 80)
print(f"🗜️ Bundling full 4-folder architecture into '{zip_filename}'...")

with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zip_file:
    for root, dirs, files_list in os.walk(base_dir):
        for file in files_list:
            abs_path = os.path.join(root, file)
            rel_path = os.path.relpath(abs_path, os.path.dirname(base_dir))
            zip_file.write(abs_path, rel_path)

print("🎉 Success! Process complete. Your download will start instantly via the browser...")
files.download(zip_filename)